#!/usr/bin/env python3
"""
Test Vector Validator using psbt_sp

This module validates test vectors generated by test_generator.py using
the psbt_sp package's robust validation capabilities.

It supports:
1. Valid test cases - Full structure and DLEQ validation
2. Invalid structure cases - Catches malformed PSBTs
3. Invalid DLEQ cases - Validates proof correctness
4. Incomplete ECDH cases - Checks coverage analysis
"""

import base64
import json
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
import sys
import os
import struct

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from psbt_sp.psbt import SilentPaymentPSBT, validate_psbt_silent_payments
from psbt_sp.crypto import UTXO
from psbt_sp.psbt_utils import check_ecdh_coverage
from psbt_sp.constants import PSBTFieldType


@dataclass
class ValidationResult:
    """Result of validating a single test vector"""
    test_name: str
    passed: bool
    stage: str  # 'structure', 'dleq', 'ecdh', 'output_scripts'
    expected_result: str  # 'valid', 'invalid_structure', 'invalid_dleq', 'incomplete_ecdh'
    errors: List[str]
    details: Dict


class TestVectorValidator:
    """Validates test vectors using psbt_sp package"""
    
    def __init__(self, verbose: bool = False):
        self.verbose = verbose
        self.results: List[ValidationResult] = []
    
    def log(self, message: str):
        """Log message if verbose mode enabled"""
        if self.verbose:
            print(message)
    
    def load_test_vector(self, test_vector: Dict) -> Optional[Tuple[SilentPaymentPSBT, List[UTXO]]]:
        """
        Load test vector and convert to psbt_sp types
        
        Args:
            test_vector: Test vector dictionary from test_vectors.json
            
        Returns:
            Tuple of (PSBT, list of UTXOs) or None if load failed
        """
        try:
            # Deserialize PSBT from base64
            from psbt_sp.serialization import parse_psbt_bytes
            
            psbt_bytes = base64.b64decode(test_vector['psbt'])
            
            # Parse PSBT bytes into field components
            global_fields, input_maps, output_maps = parse_psbt_bytes(psbt_bytes)
            
            # Create PSBT object and populate with parsed fields
            psbt = SilentPaymentPSBT()
            psbt.global_fields = global_fields
            psbt.input_maps = input_maps
            psbt.output_maps = output_maps
            
            # Convert input_keys to UTXOs
            inputs = []
            for key in test_vector['input_keys']:
                utxo = UTXO(
                    txid=key['prevout_txid'],
                    vout=key['prevout_index'],
                    amount=key['amount'],
                    script_pubkey=key['prevout_scriptpubkey'],
                    private_key=int(key['private_key'], 16) if key.get('private_key') else None
                )
                inputs.append(utxo)
            
            return psbt, inputs
            
        except Exception as e:
            self.log(f"Failed to load test vector: {e}")
            return None
    
    def validate_structure(self, psbt: SilentPaymentPSBT) -> Tuple[bool, List[str]]:
        """
        Validate PSBT structure against BIP 375 rules (basic structure only)
        
        Args:
            psbt: PSBT to validate
            
        Returns:
            Tuple of (is_valid, list_of_errors)
        """
        self.log("  [1] Structure Validation...")
        errors = []
        
        # Basic PSBT structure validation (similar to validate_psbt_silent_payments but without DLEQ)
        # Validate global fields
        has_psbt_version = False
        has_tx_version = False
        has_input_count = False
        has_output_count = False
        
        for field in psbt.global_fields:
            if field.field_type == PSBTFieldType.PSBT_GLOBAL_VERSION:
                has_psbt_version = True
                psbt_version = struct.unpack('<I', field.value_data)[0]
                if psbt_version != 2:
                    errors.append(f"Invalid PSBT version {psbt_version}, must be 2 for PSBTv2")
            elif field.field_type == PSBTFieldType.PSBT_GLOBAL_TX_VERSION:
                has_tx_version = True
                version = struct.unpack('<I', field.value_data)[0]
                if version != 2:
                    errors.append(f"Invalid transaction version {version}, must be 2 for silent payments")
            elif field.field_type == PSBTFieldType.PSBT_GLOBAL_INPUT_COUNT:
                has_input_count = True
            elif field.field_type == PSBTFieldType.PSBT_GLOBAL_OUTPUT_COUNT:
                has_output_count = True
        
        if not has_psbt_version:
            errors.append("Missing required PSBT_GLOBAL_VERSION")
        if not has_tx_version:
            errors.append("Missing required PSBT_GLOBAL_TX_VERSION")
        if not has_input_count:
            errors.append("Missing required PSBT_GLOBAL_INPUT_COUNT")
        if not has_output_count:
            errors.append("Missing required PSBT_GLOBAL_OUTPUT_COUNT")
        
        # Validate inputs (basic structure only)
        for i, input_fields in enumerate(psbt.input_maps):
            input_field_dict = {field.field_type: field for field in input_fields}
            
            # Check SIGHASH_ALL requirement
            if PSBTFieldType.PSBT_IN_SIGHASH_TYPE in input_field_dict:
                sighash_field = input_field_dict[PSBTFieldType.PSBT_IN_SIGHASH_TYPE]
                if len(sighash_field.value_data) >= 4:
                    sighash_type = struct.unpack('<I', sighash_field.value_data[:4])[0]
                    if sighash_type != 1:  # SIGHASH_ALL
                        errors.append(f"Input {i} uses non-SIGHASH_ALL ({sighash_type}) with silent payments")
            
            # Check segwit version restriction (BIP 375: only v0 and v1 allowed)
            if PSBTFieldType.PSBT_IN_WITNESS_UTXO in input_field_dict:
                witness_utxo = input_field_dict[PSBTFieldType.PSBT_IN_WITNESS_UTXO].value_data
                if len(witness_utxo) >= 9:
                    script_len = witness_utxo[8]
                    if len(witness_utxo) >= 9 + script_len:
                        script = witness_utxo[9:9 + script_len]
                        # Check if script starts with OP_2 or higher (segwit v2+)
                        if len(script) >= 1 and script[0] >= 0x52:  # OP_2 or higher
                            errors.append(f"Input {i} uses segwit version > 1 with silent payments")
        
        # Note: We do NOT check ECDH/DLEQ pairing at structure validation level
        # That is handled at DLEQ verification stage per BIP 375
        
        # Validate outputs per BIP375 (basic structure only)
        for i, output_fields in enumerate(psbt.output_maps):
            output_field_dict = {field.field_type: field for field in output_fields}
            
            # BIP375: PSBT_OUT_SCRIPT is optional for silent payment outputs
            # Each output must have either PSBT_OUT_SCRIPT or PSBT_OUT_SP_V0_INFO (or both)
            has_script = PSBTFieldType.PSBT_OUT_SCRIPT in output_field_dict
            has_sp_info = PSBTFieldType.PSBT_OUT_SP_V0_INFO in output_field_dict
            
            if not has_script and not has_sp_info:
                errors.append(f"Output {i} must have either PSBT_OUT_SCRIPT or PSBT_OUT_SP_V0_INFO")
            
            # Validate PSBT_OUT_SP_V0_INFO if present
            if has_sp_info:
                sp_info = output_field_dict[PSBTFieldType.PSBT_OUT_SP_V0_INFO]
                if len(sp_info.value_data) != 66:  # 33 + 33 bytes (scan_key + spend_key)
                    errors.append(f"Output {i} SP_V0_INFO has invalid length {len(sp_info.value_data)}, expected 66 bytes")
            
            # Check amount is present
            if PSBTFieldType.PSBT_OUT_AMOUNT not in output_field_dict:
                errors.append(f"Output {i} missing required amount field")
        
        is_valid = len(errors) == 0
        if is_valid:
            self.log(f"     [PASS] Structure valid")
        else:
            self.log(f"     [FAIL] Structure invalid:")
            for error in errors:
                self.log(f"        - {error}")
        
        return is_valid, errors
    
    def validate_dleq_proofs(self, psbt: SilentPaymentPSBT, inputs: List[UTXO]) -> Tuple[bool, List[str]]:
        """
        Validate all DLEQ proofs in PSBT
        
        Args:
            psbt: PSBT with DLEQ proofs
            inputs: UTXOs with private keys for verification
            
        Returns:
            Tuple of (all_valid, list_of_errors)
        """
        self.log("  [2] DLEQ Proof Verification...")
        
        try:
            is_valid = psbt.verify_dleq_proofs(inputs)
            if is_valid:
                self.log(f"     [PASS] All DLEQ proofs verified")
                return True, []
            else:
                self.log(f"     [FAIL] DLEQ proof verification failed")
                return False, ["DLEQ proof verification failed"]
        except Exception as e:
            self.log(f"     [FAIL] DLEQ verification error: {e}")
            return False, [f"DLEQ verification error: {e}"]
    
    def validate_ecdh_coverage(self, psbt: SilentPaymentPSBT) -> Tuple[bool, List[int], List[str]]:
        """
        Check ECDH coverage and identify which inputs are covered
        
        Args:
            psbt: PSBT to analyze
            
        Returns:
            Tuple of (is_complete, covered_input_indices, list_of_errors)
        """
        self.log("  [3] ECDH Coverage Analysis...")
        
        try:
            is_complete, covered_inputs = psbt.check_ecdh_coverage()
            total_inputs = len(psbt.input_maps)
            
            if is_complete:
                self.log(f"     [PASS] Complete ECDH coverage ({total_inputs}/{total_inputs} inputs)")
            else:
                self.log(f"     [WARN] Incomplete ECDH coverage ({len(covered_inputs)}/{total_inputs} inputs)")
                self.log(f"        Covered inputs: {covered_inputs}")
            
            return is_complete, covered_inputs, []
            
        except Exception as e:
            self.log(f"     [FAIL] ECDH coverage error: {e}")
            return False, [], [f"ECDH coverage error: {e}"]
    
    def validate_output_scripts(self, psbt: SilentPaymentPSBT) -> Tuple[bool, List[str]]:
        """
        Attempt to compute output scripts (only if ECDH is complete)
        
        Args:
            psbt: PSBT with complete ECDH shares
            
        Returns:
            Tuple of (success, list_of_errors)
        """
        self.log("  [4] Output Script Computation...")
        
        is_complete, _ = psbt.check_ecdh_coverage()
        if not is_complete:
            self.log(f"     [SKIP] Incomplete ECDH coverage")
            return True, []
        
        try:
            psbt.compute_output_scripts()
            self.log(f"     [PASS] Output scripts computed successfully")
            return True, []
        except Exception as e:
            self.log(f"     [FAIL] Output script computation failed: {e}")
            return False, [f"Output script computation failed: {e}"]
    
    def validate_test_vector(self, test_vector: Dict) -> ValidationResult:
        """
        Validate a single test vector
        
        Args:
            test_vector: Test vector from test_vectors.json
            
        Returns:
            ValidationResult with details of validation
        """
        test_name = test_vector.get('comment', 'unknown')
        expected_result = test_vector.get('expected_result', 'valid')
        
        self.log(f"\n[TEST] Validating: {test_name}")
        self.log(f"   Description: {test_vector.get('description', 'N/A')}")
        self.log(f"   Expected: {expected_result}")
        
        # Load test vector
        loaded = self.load_test_vector(test_vector)
        if loaded is None:
            return ValidationResult(
                test_name=test_name,
                passed=False,
                stage='load',
                expected_result=expected_result,
                errors=['Failed to load test vector'],
                details={}
            )
        
        psbt, inputs = loaded
        details = {}
        all_errors = []
        
        # Stage 1: Structure validation
        struct_valid, struct_errors = self.validate_structure(psbt)
        details['structure'] = {
            'valid': struct_valid,
            'errors': struct_errors
        }
        
        # Stage 2: DLEQ proof verification (if structure is valid or expected to be invalid)
        if struct_valid or expected_result in ['invalid_dleq']:
            dleq_valid, dleq_errors = self.validate_dleq_proofs(psbt, inputs)
            details['dleq'] = {
                'valid': dleq_valid,
                'errors': dleq_errors
            }
            all_errors.extend(dleq_errors)
        
        # Stage 3: ECDH coverage analysis
        if struct_valid and details.get('dleq', {}).get('valid', True):
            ecdh_complete, covered, ecdh_errors = self.validate_ecdh_coverage(psbt)
            details['ecdh'] = {
                'complete': ecdh_complete,
                'covered_inputs': covered,
                'errors': ecdh_errors
            }
            all_errors.extend(ecdh_errors)
        
        # Stage 4: Output script computation
        if struct_valid and details.get('ecdh', {}).get('complete', False):
            scripts_valid, script_errors = self.validate_output_scripts(psbt)
            details['output_scripts'] = {
                'valid': scripts_valid,
                'errors': script_errors
            }
            all_errors.extend(script_errors)
        
        # Assess result
        passed = self._assess_result(test_name, expected_result, struct_valid, details, struct_errors)
        
        stage = 'complete'
        if not struct_valid and expected_result != 'invalid_structure':
            stage = 'structure'
        elif not details.get('dleq', {}).get('valid', True) and expected_result != 'invalid_dleq':
            stage = 'dleq'
        elif not details.get('ecdh', {}).get('complete', False) and expected_result != 'incomplete_ecdh':
            stage = 'ecdh'
        
        return ValidationResult(
            test_name=test_name,
            passed=passed,
            stage=stage,
            expected_result=expected_result,
            errors=all_errors,
            details=details
        )
    
    def _assess_result(self, test_name: str, expected: str, struct_valid: bool,
                       details: Dict, struct_errors: List[str]) -> bool:
        """
        Assess whether test result matches expectation
        
        Args:
            test_name: Name of test
            expected: Expected result type
            struct_valid: Whether structure validation passed
            details: Validation details
            struct_errors: Structure validation errors
            
        Returns:
            True if result matches expectation
        """
        if expected == 'valid':
            # All stages should pass
            passed = (
                struct_valid and
                details.get('dleq', {}).get('valid', True) and
                details.get('ecdh', {}).get('complete', False) and
                details.get('output_scripts', {}).get('valid', True)
            )
            if passed:
                self.log(f"   [PASS] Valid test vector validated successfully")
            else:
                self.log(f"   [FAIL] Valid test vector failed validation")
            return passed
        
        elif expected == 'invalid_structure':
            # Structure validation should fail
            passed = not struct_valid
            expected_error = details.get('expected_error_contains')
            if passed and expected_error:
                passed = any(expected_error in err for err in struct_errors)
            
            if passed:
                self.log(f"   [PASS] Valid test vector passed all checks")
            else:
                self.log(f"   [FAIL] Valid test vector failed validation")
            return passed
        
        elif expected == 'invalid_structure':
            # Structure validation should fail
            passed = not struct_valid
            expected_error = details.get('expected_error_contains')
            if passed and expected_error:
                passed = any(expected_error in err for err in struct_errors)
            
            if passed:
                self.log(f"   [PASS] Invalid structure detected correctly")
            else:
                self.log(f"   [FAIL] Invalid structure not detected")
            return passed
        
        elif expected == 'invalid_dleq':
            # Structure should be valid but DLEQ verification should fail
            dleq_valid = details.get('dleq', {}).get('valid', False)
            passed = struct_valid and not dleq_valid
            
            if passed:
                self.log(f"   [PASS] Invalid DLEQ proof detected correctly")
            else:
                self.log(f"   [FAIL] Invalid DLEQ proof not detected")
            return passed
        
        elif expected == 'incomplete_ecdh':
            # ECDH coverage should be incomplete
            ecdh_complete = details.get('ecdh', {}).get('complete', False)
            passed = struct_valid and not ecdh_complete
            
            if passed:
                self.log(f"   [PASS] Incomplete ECDH coverage detected correctly")
            else:
                self.log(f"   [FAIL] Incomplete ECDH coverage not detected")
            return passed
        
        else:
            self.log(f"   [WARN] Expected result type '{expected}' not recognized")
            return False
    
    def validate_all(self, test_vectors: List[Dict]) -> Dict:
        """
        Validate all test vectors
        
        Args:
            test_vectors: List of test vectors
            
        Returns:
            Dictionary with validation summary
        """
        self.results = []
        
        for test_vector in test_vectors:
            result = self.validate_test_vector(test_vector)
            self.results.append(result)
        
        return self.summarize()
    
    def summarize(self) -> Dict:
        """
        Summarize validation results
        
        Returns:
            Summary dictionary
        """
        total = len(self.results)
        passed = sum(1 for r in self.results if r.passed)
        failed = total - passed
        
        failed_tests = [r for r in self.results if not r.passed]
        
        summary = {
            'total': total,
            'passed': passed,
            'failed': failed,
            'pass_rate': f"{100 * passed / total:.1f}%" if total > 0 else "N/A",
            'failed_tests': [
                {
                    'name': r.test_name,
                    'expected': r.expected_result,
                    'stage': r.stage,
                    'errors': r.errors
                }
                for r in failed_tests
            ]
        }
        
        return summary
    
    def print_summary(self):
        """Print validation summary to stdout"""
        summary = self.summarize()
        
        print("\n" + "=" * 70)
        print("VALIDATION SUMMARY")
        print("=" * 70)
        print(f"Total Tests:  {summary['total']}")
        print(f"Passed:       {summary['passed']}")
        print(f"Failed:       {summary['failed']}")
        print(f"Pass Rate:    {summary['pass_rate']}")
        
        if summary['failed'] > 0:
            print("\n[FAILED TESTS]:")
            for failed in summary['failed_tests']:
                print(f"\n  {failed['name']}")
                print(f"    Expected: {failed['expected']}")
                print(f"    Failed at: {failed['stage']}")
                for error in failed['errors']:
                    print(f"    - {error}")
        else:
            print("\n[PASS] All tests passed!")
        
        print("=" * 70 + "\n")
        
        return summary['failed'] == 0


def validate_test_vectors_file(filepath: str, verbose: bool = False) -> bool:
    """
    Convenience function to validate all test vectors in a file
    
    Args:
        filepath: Path to test_vectors.json
        verbose: Enable verbose logging
        
    Returns:
        True if all tests passed
    """
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    # Process invalid test vectors
    invalid_tests = []
    for test in data.get('invalid', []):
        # Set expected_result based on test description and comment
        description = test.get('description', '').lower()
        comment = test.get('comment', '').lower()
        if 'missing dleq' in description or 'invalid dleq' in description or 'missing dleq' in comment or 'dleq' in comment:
            test['expected_result'] = 'invalid_dleq'
        elif 'sighash' in description or 'segwit' in description or 'wrong sp' in description:
            test['expected_result'] = 'invalid_structure'
        elif 'no ecdh' in description:
            test['expected_result'] = 'incomplete_ecdh'
        else:
            test['expected_result'] = 'invalid_structure'  # default for invalid tests
        invalid_tests.append(test)
    
    # Process valid test vectors
    valid_tests = []
    for test in data.get('valid', []):
        test['expected_result'] = 'valid'
        valid_tests.append(test)
    
    test_vectors = invalid_tests + valid_tests
    
    validator = TestVectorValidator(verbose=verbose)
    validator.validate_all(test_vectors)
    
    return validator.print_summary()


if __name__ == '__main__':
    import argparse
    from pathlib import Path

    # Default path: look for test_vectors.json in parent directory (bip-0375 root)
    default_test_file = Path(__file__).parent.parent / 'test_vectors.json'

    parser = argparse.ArgumentParser(description='Validate BIP 375 test vectors using psbt_sp')
    parser.add_argument('-f', '--file', default=str(default_test_file),
                       help='Path to test_vectors.json (default: ../test_vectors.json)')
    parser.add_argument('-v', '--verbose', action='store_true',
                       help='Enable verbose logging')

    args = parser.parse_args()

    if not os.path.exists(args.file):
        print(f"[ERROR] File not found: {args.file}")
        sys.exit(1)

    all_passed = validate_test_vectors_file(args.file, verbose=args.verbose)
    sys.exit(0 if all_passed else 1)
